### ISSUE TITLE
Newtonsoft.Json (>= 11.0.1)

### ISSUE THREAD

**Issue by TonyHenrique** [boletofacil/boletofacil-sdk-net#1]
Olá, pretendo usar este NuGet no Azure Functions, mas lá o **Newtonsoft.Json (= 9.0.1)**

Vocês poderiam gerar um novo NuGet com a versão exigida menor, **>= 9.0.1** ?

**Comment by marco-boleto** [comment]
Olá, Tony!


Essa é uma limitação do Azure Functions. Há alguns tópicos onde ela já está sendo tratada, como, por exemplo: https://github.com/Azure/azure-functions-vs-build-sdk/issues/107

Sobre o downgrade do requisito, não há possibilidade de ser feito por nós (as próximas versões provavelmente terão o upgrade para a versão 11),contudo, o código do SDK é aberto: você pode baixá-lo e fazer as alterações específicas para sua necessidade.

**Comment by TonyHenrique** [comment]
Só para você ter uma ideia, eu pedi a mesma coisa para o pessoal do driver do banco de dados e eles fizeram isto em poucas horas, porque não impactava o projeto e daria mais compatibilidade, ter a versão do **Newtonsoft.Json (>= 9.0.1)**

De qualquer forma espero em breve que isto seja resolvido no Azure Functions, e ainda bem que temos acesso ao fonte do SDK Boleto Fácil para este tipo de coisa.

Mas eu pedi para evitar ter que mexer no código fonte, seria só **abaixar a versão mínima exigida** e seria possível usar o NuGet sem problemas.

**Comment by marco-boleto** [comment]
OK. Vamos analisar essa possibilidade, e assim que tivermos uma posição, lhe informamos.

**Comment by TonyHenrique** [comment]
Obrigado!

O SDK do MercadoPago também fez esta alteração que sugeri, veja https://github.com/mercadopago/dx-dotnet/issues/41#event-1679309922

**Comment by marco-boleto** [comment]
Olá!

Feito. Versão 1.0.5 disponível com a versão mínima requerida baixada para a 9.0.1.

**Comment by TonyHenrique** [comment]
Valeu, testei aqui o NuGet boletofacilsdk 1.0.5, no Sandbox, na função Consulta Saldo e funcionou na hora no Azure Functions (v2)!
